PUT http://localhost:3000/api/users/0bf46f69-811f-4886-b6ca-cfbd75b01c81
Cookie: authjs.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiRC1CVl9NSnVFU056aWFTM3YxT0ppdlhQcmV4ZXhES2syVDRBOVEtZzk5MEluclhfQ3g0dTdQc3Btd1JwUkFmTUdwZzRpd2l5SXhPV1FXeFNPRFA1WXcifQ..jyrNO0Q_xdIt7xbJwcM8pQ.XnguYPJSwteFV5SX23Q3AiVb81Hk3NRAPALTcENwBu5YoQgdUmjr660G1v9PCcmaWguitR6JmlH4Vv1tWq2ZDDzjyJ_qSjgJJCyCOWoq8B8hSvNUtwCokTIYr8BOzKiDbNRVON-ZIcsQ27BEeRbOwXhUXTkSb8W643K7NATMHJxXolb0k0JtiuV0_k9JA0NfznlGd8cN7LAclipE-dp_l2v1_ylARX3k73UWt8hCWR0HFjWlQdjjG0yAKryaRh06nh2wNGILwcp5qpWnxk-RnvkbfX6_bBVsud7Oak8vW0ApJiaTqHFAVkJOBfLk3J7Hl99ITi62BTsyjQ5fObf5jGZgmkzKkT7eLt0m9vIJrzFrrk2VWOT9c2Uz6h7thJYhCBxD1YXq6cKhQmeRCJfwKaJzvn9SJ6SZu5dDi7ajtAjL5d0WwLFW0MFx7bR9abVJAWCxiSVbX0ubLhrGJQ7-Ww.d2xyPyZNDZTjJ282tNxbXY1NTmTLiZNLnqt-uGplUxQ
Content-Type: application/json

{
  "username": "hatohui"
}