export const QUOTES = [
  "Your upcoming events sucks!",
  "Don't forget to check your schedule!",
  "Make sure to attend your events!",
  "Your events are waiting for you!",
  "Stay organized with your events!",
  "Don't miss out on your events!",
  "Your events are important, keep track of them!",
  "Stay on top of your events!",
  "Bro, your events are calling you!",
  "Infurnity misses you!",
  "Will you be my love?",
  "Hee hee hee hee hee hee hee hee hee hee",
  "I am the one who knocks!",
  "Winter is coming!",
  "May the Force be with you!",
  "To infinity and beyond!",
  "I solemnly swear that I am up to no good.",
  "Just keep swimming!",
  "Elementary, my dear Watson.",
  "I'm not a doctor, but I play one on TV.",
  "You can't handle the truth!",
  "Here's looking at you, kid.",
  "I feel the need—the need for speed!",
  "Carpe diem. Seize the day",
  "Dragons are real, and they are coming.",
  "Rawr uwu (>^_^)> <(^_^<) ^(^_^)^ v(^_^)v",
  "Did you know this year Furum will be different?",
  "Stupid Yaoyao",
  "I am Groot.",
  "Bryan is one stinky demon fox :3",
  "Cardspire is my waifu <3",
  "Skylar is a bitch :3",
  "Edwin Lim hehehehehee",
  "Fuck you oayoay",
];
